# Generated by Django 2.0.4 on 2018-06-18 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageDomains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('display', models.CharField(max_length=50)),
                ('audience', models.CharField(max_length=50)),
            ],
            options={
                'permissions': (('has_officer_access', 'members with officer site access'),),
            },
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('display', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=150)),
                ('content', models.CharField(max_length=10000)),
                ('pageType', models.CharField(max_length=50)),
                ('pageDomain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.PageDomains')),
            ],
        ),
    ]
