# Generated by Django 2.0.4 on 2018-06-04 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='Menu',
            new_name='menu',
        ),
    ]
