# Generated by Django 2.0.4 on 2018-06-15 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_penguin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='penguin',
            options={'permissions': (('can_view_penguins', 'can_play_with_penguines'),)},
        ),
    ]
