# Generated by Django 2.0.4 on 2018-06-15 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180615_2103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='penguin',
            options={},
        ),
    ]
