# Generated by Django 2.0.4 on 2018-06-15 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180615_2104'),
    ]

    operations = [
    ]
