# Generated by Django 2.0.4 on 2018-06-15 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20180615_2108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='penguin',
            options={'permissions': (('can_see_penguins', 'Ability to see penguins'),)},
        ),
    ]
