# Generated by Django 2.0.4 on 2018-06-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20180615_2115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'permissions': (('can_access_member_menu', 'ministry members with member site access'), ('can_access_officer_menu', 'ministry officers with officer site access'))},
        ),
        migrations.AddField(
            model_name='menu',
            name='audience',
            field=models.CharField(default='public', max_length=50),
            preserve_default=False,
        ),
    ]
